# Generated by Django 4.1 on 2022-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="description", field=models.TextField(),
        ),
    ]
