# Generated by Django 4.1 on 2022-08-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=200),
        ),
    ]
