# Generated by Django 4.1 on 2022-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog", old_name="data_record", new_name="data_blog",
        ),
    ]
