# Generated by Django 4.1 on 2022-08-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_data_record_blog_data_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="data_blog", field=models.DateField(),
        ),
    ]
