# Generated by Django 4.1 on 2022-08-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_blog_new_delete_blog"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blog_New", new_name="Blog",),
    ]
